Created a local variable for ProxiedPlayers
ViaVersion/ViaVersion pull request #2198
Opened 2020-11-15 20:16 UTC by terrarier2111

2020-12-09 19:40 UTC, terrarier2111 commented
@KennyTV could you approve this changes please?

2020-12-09 21:35 UTC, mdcfe requested changes

2020-12-09 21:35 UTC, mdcfe commented on bungee/src/main/java/us/myles/ViaVersion/BungeePlugin.java
> +        ViaCommandSender[] array = new ViaCommandSender[players.size()];
```suggestion
        ViaCommandSender[] array = new ViaCommandSender[getProxy().getPlayers().size()];
```

2020-12-09 21:35 UTC, mdcfe commented on bungee/src/main/java/us/myles/ViaVersion/BungeePlugin.java
> +        for (ProxiedPlayer player : players) {
```suggestion
        for (ProxiedPlayer player : getProxy().getPlayers()) {
```

2020-12-09 21:36 UTC, mdcfe commented on bungee/src/main/java/us/myles/ViaVersion/BungeePlugin.java
> +import java.util.Collection;
```suggestion
```

2020-12-10 13:17 UTC, terrarier2111 commented
You essentially told me to revert all changes i made is there any reason for this and if so could you please tell me the reason.

2020-12-11 09:17 UTC, merged

2020-12-11 09:17 UTC, FormallyMyles commented
Thanks!