Implement showShieldWhenSwordInHand option
ViaVersion/ViaVersion pull request #2417
Opened 2021-04-02 14:42 UTC by LabyStudio

We are trying to improve pvp on 1.8 servers for players on the latest Minecraft version.
So I implemented another way to block without delay because the feature of #2415 causes problems with anti cheats.

The idea is that you have a shield in your second hand while you have a sword in your main hand.
The shield disappears as soon as you switch to another item.

The blocking interaction is on the shield and causes a client-side slowdown which is the expected behavior of the anti cheat.
I added an option called "show-shield-when-sword-in-hand" to toggle this feature.

![demo](https://user-images.githubusercontent.com/8986505/113424821-184bc980-93d1-11eb-898e-2815523f1317.gif)

2021-04-03 11:12 UTC, KennyTV requested changes
Isn't this missing incoming creative inv packets?

2021-04-03 11:12 UTC, KennyTV commented on common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/InventoryPackets.java
> +                                entityTracker.syncShieldWithSword();
No need to call syncShieldWithSword with each single item transaction, move this outside of the for loop

2021-04-03 11:12 UTC, KennyTV commented on common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/storage/InventoryTracker.java
> +        if(hoverSlot != 45) {
Early return with if (==45) {return;}

2021-04-03 11:12 UTC, KennyTV commented on common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/storage/EntityTracker1_9.java
> +        setSecondHand(isSword ? shield : null);
This should be short-circuited; if the itemId is null/0, set to null immediately, else also only create the shield Item instance if it actually is a sword

2021-04-03 19:09 UTC, LabyStudio commented
> Isn't this missing incoming creative inv packets?

Sorry, I didn't notice that. It should work now!

2021-04-03 19:49 UTC, KennyTV commented
Moving your mouse while placing a sword with right click doesn't seem to update the item cache correctly

2021-04-04 07:12 UTC, KennyTV commented
I can't tell you what exactly is wrong, but after some dragging and hotbar swapping I could desync it 👀

2021-04-04 07:43 UTC, LabyStudio commented
> I can't tell you what exactly is wrong, but after some dragging and hotbar swapping I could desync it 👀

Hm. I tried that for 10 minutes straight with multiple people.
I will look into it

2021-04-04 12:26 UTC, KennyTV requested changes

2021-04-04 12:26 UTC, KennyTV commented on common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/storage/InventoryTracker.java
> +                System.out.println("cleared window " + windowId + ", we have " + windowItemCache.size() + " remaining");
👀

2021-04-04 12:26 UTC, KennyTV commented on common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/storage/EntityTracker1_9.java
> +    public void syncShieldWithSword(boolean forceUpdate) {
The parameter is only ever set to false in its usages

2021-04-04 12:36 UTC, KennyTV approved these changes
*Should* be alright, I'm going to wait 1-2 days in case anyone else ~~actually willing to go through 1.8 protocol code~~ has something to say on this.

2021-04-05 16:53 UTC, KennyTV commented
Alright then, fingers crossed, thank you for the contribution! 🐱‍🏍

2021-04-05 16:53 UTC, merged