Improve arm-swing cancel by resetting cursor item
ViaVersion/ViaVersion pull request #2528
Opened 2021-06-10 18:19 UTC by tomcraft

Improvements of #2031 and #2007 , based on @Gerrygames [comment](https://github.com/ViaVersion/ViaVersion/pull/2031#issuecomment-678677104) and help with his [code snippet on Discord](https://discord.com/channels/316206679014244363/316218802155028482/852582496986333254).

As @Gerrygames said in his comment and on Discord, the source of the issue is that the client tries to drop the item in cursor during navigation between multiple inventories. This was causing an arm swing animation packet to be sent and processed by server as an interaction.

Previous PR was cancelling any arm animation packet while an inventory is open. This required tracking inventories open and close and the arm was this swinging client-side. It worked well with 1.16 but with 1.17 the packet order changed and the animation packet is now sent after the inventory closed, causing the issue to reappear. So it is now impossible to track for inventory state for 1.17.

This PR clears the cursor item before `WINDOW_OPEN` and before `WINDOW_CLOSE` to prevent client to try dropping any item. Clearing at `WINDOW_OPEN` prevents drop during navigation, and `WINDOW_CLOSE` prevents drop at the very end when a click on an item closes the inventory. As a logical effect, there is no more client-side arm swing.

I also removed the now unused InventoryTracker that was introduced to track windowId.

All feedbacks are welcome :)

2021-06-15 12:52 UTC, tomcraft commented
just fixed the way i registered remappers

2021-06-20 04:53 UTC, RednedEpic commented
LGTM, definitely seems to be a more proper fix for the issue.

2021-06-20 05:18 UTC, connorhartley commented
I agree, LGTM.

2021-06-20 07:20 UTC, KennyTV requested changes
Looks good otherwise

2021-06-20 07:20 UTC, KennyTV commented on common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/packets/InventoryPackets.java
> +            clearPacket.write(Type.BYTE, (byte)-1);
the type was changed 1/2 days ago
```suggestion
            clearPacket.write(Type.UNSIGNED_BYTE, (byte)-1);
```

2021-06-20 07:20 UTC, KennyTV commented on common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/packets/InventoryPackets.java
> +            wrapper.passthroughAll();
that line isn't needed

2021-06-20 09:15 UTC, tomcraft commented
Applied kneny's suggestions

2021-06-20 20:50 UTC, KennyTV approved these changes

2021-06-20 20:50 UTC, merged