reduce World#isChunkLoaded usage for cached Chunk instance
ViaVersion/ViaVersion pull request #2600
Opened 2021-07-03 16:47 UTC by tomcraft

i think it is safe to ignore this check for the `lastChunk` Chunk instance, i've been running a similar behavior implementation based on NMS for many month without issue.

feel free to comment :)

2021-07-03 16:51 UTC, kennytv requested changes
Nope, the chunk might have been unloaded already.

2021-07-03 17:09 UTC, tomcraft commented
Oke, I don't see much more to do here without big changes.

2021-07-03 17:09 UTC, closed without merging

2021-07-08 22:02 UTC, andreasdc commented
@kennytv what's the point in caching lastChunk then?

2021-07-09 08:00 UTC, kennytv commented
Because this reduces the risk of issues (like cancelling unloads) due to concurrency issues, which block connection methods are still full of.

2021-07-09 10:50 UTC, andreasdc commented
You are right, but 1 single getChunkIfLoaded would be better right?

2021-07-09 10:53 UTC, kennytv commented
That doesn't exist in these old versions, and we are not interested in doing bytecode hacks or using version dependent reflection to get them.

2021-07-09 10:58 UTC, andreasdc commented
That doesn't answer my question, but I understand, thanks. :)

2021-07-09 13:01 UTC, andreasdc commented
@kennytv isn't this method called on loaded chunks? Like placing blocks etc.?