Handle errors properly in <= 1.20 custom payload reading
ViaVersion/ViaVersion pull request #3770
Opened 2024-04-03 22:29 UTC by FlorianMichael

This PR fixes pre 1.20 custom payload handling, Minecraft try catched the whole data/content reading code causes errors to *silently* fail, here the pre 1.20 custom payload handler:
<img width="660" alt="image" src="https://github.com/ViaVersion/ViaVersion/assets/60033407/d3416097-8fe4-45f8-af94-cb72aafa16e5">

Therefore I introduced PacketHandlers#handleSoftFail to line up with older protocols code

2024-04-03 22:31 UTC, RaphiMC approved these changes

2024-04-04 20:20 UTC, kennytv requested changes

2024-04-04 20:20 UTC, kennytv commented on common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_2to1_20/Protocol1_20_2To1_20.java
> +                    final String channel = wrapper.get(Type.STRING, 0);
Key.namespaced

2024-04-04 20:22 UTC, FlorianMichael commented on common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_2to1_20/Protocol1_20_2To1_20.java
> +                    final String channel = wrapper.get(Type.STRING, 0);
see field below

2024-04-04 20:23 UTC, kennytv commented on common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_2to1_20/Protocol1_20_2To1_20.java
> +                    final String channel = wrapper.get(Type.STRING, 0);
huh?

2024-04-04 20:23 UTC, kennytv commented on common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_2to1_20/Protocol1_20_2To1_20.java
> +                    final String channel = wrapper.get(Type.STRING, 0);
huh?

2024-04-04 20:24 UTC, FlorianMichael commented on common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_2to1_20/Protocol1_20_2To1_20.java
> +                    final String channel = wrapper.get(Type.STRING, 0);
Fixed, I am just stupid

2024-04-04 20:24 UTC, kennytv approved these changes

2024-04-04 20:25 UTC, merged