Fix custom item names not being italic in 1.12->1.13
ViaVersion/ViaVersion pull request #3868
Opened 2024-05-19 21:52 UTC by FlorianMichael

Looking at the git history and the old code it seems that this was missed previously, item name in 1.12->1.13 and item lore in 1.13->1.14 should both be italic default (I tested this using native server and client versions).

2024-05-19 22:03 UTC, Kichura approved these changes

2024-05-20 07:18 UTC, kennytv requested changes
This will break items with color formatting

2024-05-20 15:06 UTC, FlorianMichael commented
Did some testing with various items with custom name and lore on a 1.12 server with both 1.12 and 1.16 client and they look equal now, tested items:

minecraft:fishing_rod 1 0 {display:{Lore:["§aHello","§b§kWorld"]}}
minecraft:fishing_rod 1 0 {display:{Lore:["Test"]}}
minecraft:stone 1 0 {display:{Name:"Test"}}
minecraft:stone 1 0 {display:{Name:"§aTest"}}

2024-05-21 09:30 UTC, kennytv approved these changes

2024-05-21 09:30 UTC, merged