Handle items with invalid amount in 1.20.3->.5
ViaVersion/ViaVersion pull request #3889
Opened 2024-05-28 22:49 UTC by FlorianMichael

1.20.4 can send items which have a bigger amount than vanilla usually accepts, and the client doesn't validate it, 1.20.5 on the other hand checks against MAX_STACK_SIZE, meaning we should set MAX_STACK_SIZE to always have the item amount to emulate old behavior. Inventory actions are broken in both versions after sending an iron sword with a stack size of 64, so /shrug about that.

Fixes https://github.com/ViaVersion/ViaVersion/issues/3882

2024-05-28 22:54 UTC, AoElite commented
Tested it & it does appear to fix https://github.com/ViaVersion/ViaVersion/issues/3882

2024-05-29 06:56 UTC, RaphiMC commented
Won't this cause items to be unmergable clientside? If the player has two half stacks of stone (32) and tries to merge them into one stack (64) won't that cause issues if the client thinks that the stack is already full (because 32 is the max stack size of each)

2024-05-29 08:02 UTC, kennytv requested changes
Needs a config option, defaulting to false

2024-05-29 11:31 UTC, FlorianMichael commented
@RaphiMC right, the fix should only apply if the item amount is larger than the correct max stack size

2024-05-29 13:02 UTC, FlorianMichael commented
Added a setting for it as well as proper validation if the fix is really needed

2024-05-29 14:46 UTC, merged