Improve some grammar and rename update checker setting
ViaVersion/ViaVersion pull request #3900
Opened 2024-06-01 20:22 UTC by FlorianMichael

2024-06-02 07:01 UTC, kennytv requested changes

2024-06-02 07:01 UTC, kennytv commented on common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
> -        checkForUpdates = getBoolean("checkforupdates", true);
Needs handling of the old field

2024-06-02 13:39 UTC, FlorianMichael commented on common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
> -        checkForUpdates = getBoolean("checkforupdates", true);
Done

2024-06-03 19:31 UTC, FlorianMichael commented
Removed handling for the old value again so we don't need to do major changes to the config system just for it.

2024-06-04 10:41 UTC, kennytv approved these changes

2024-06-04 10:41 UTC, merged