Add some more registerClientbound/Serverbound combinations to the Protocol interface
ViaVersion/ViaVersion pull request #4113
Opened 2024-08-21 18:24 UTC by FlorianMichael

Some combinations with the override boolean for ViaFabricPlus and other addons

2024-08-22 09:00 UTC, FlorianMichael commented
I only added those which I would use but I can remove the ones you don't like.

2024-08-25 17:14 UTC, kennytv requested changes
Actually, none of these are "standard" or needed for the main projects, helper methods are better added in the projects that need them

2024-08-25 17:14 UTC, kennytv commented on common/src/main/java/com/viaversion/viaversion/protocols/v1_12_2to1_13/Protocol1_12_2To1_13.java
> +        registerClientbound(State.LOGIN, ClientboundLoginPackets.LOGIN_DISCONNECT.getId(), wrapper -> {
all of these can already just be replaced with
```java
registerClientbound(State.LOGIN, ClientboundLoginPackets.LOGIN_DISCONNECT, wrapper -> {
```
etc.

2024-08-25 18:24 UTC, FlorianMichael commented
I'll keep those extra methods in ViaFabricPlus then; Resolved the suggestion

2024-08-28 13:52 UTC, kennytv approved these changes

2024-08-28 13:52 UTC, merged