Fix footstep particle causing null kick
ViaVersion/ViaVersion pull request #4287
Opened 2024-11-27 01:29 UTC by lowercasebtw

Added checks for when getMappingData returns null and getParticleMappings returns null.

Also swapped the equals check around to stop null issues.

This fixes the recent bug I found when playing 1.8.x bedwarspractice and was getting kicked when using invis and the footstep particles spawned.

2024-11-27 09:35 UTC, lowercasebtw commented
Fixed

2024-11-27 20:56 UTC, FlorianMichael requested changes

2024-11-27 20:56 UTC, FlorianMichael commented on common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/rewriter/ParticleRewriter1_21_2.java
> +        ParticleMappings particleMappings = protocol.getMappingData().getParticleMappings();
Revert this change/diff again, no need for the extra field

2024-11-27 22:24 UTC, lowercasebtw commented
Done

2024-11-28 11:04 UTC, kennytv approved these changes

2024-11-28 11:05 UTC, merged